version: '3.7'

services:

  vis:
    build:
      context: vis
    links:
      - d2r
      - loadsheets
      - stats-registry
    environment:
      - VIRTUAL_HOST=ons.floop.org.uk
      - LETSENCRYPT_HOST=ons.floop.org.uk
      - LETSENCRYPT_EMAIL=alex@floop.org.uk
    restart: always
    networks:
      - cloudfluff_proxy
      - default

  sqldb:
    build:
      context: sqldb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=solarsystem
      - MYSQL_USER=solar
      - MYSQL_PASSWORD=system
    volumes:
      - mariadb:/var/lib/mysql:z
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  d2r:
    image: cloudfluff/d2r
    volumes:
      - solardata:/var/lib/d2rq:z
    environment:
      - D2R_BASEURI=https://ons.floop.org.uk/
    links:
      - sqldb
    restart: always

  loadsheets:
    build:
      context: sheets
    volumes:
      - solardata:/data:z
    links:
      - sqldb
    restart: always

  stats-registry:
    build:
      context: registries
    volumes:
      - registry:/registry:z
    links:
      - sqldb

volumes:
  mariadb:
  solardata:
  registry:

networks:
  cloudfluff_proxy:
    external: true
