version: '2'

services:

  vis:
    build:
      context: vis
    links:
      - d2r
      - loadsheets
    environment:
      - VIRTUAL_HOST=ons.floop.org.uk
      - LETSENCRYPT_HOST=ons.floop.org.uk
      - LETSENCRYPT_EMAIL=alex@floop.org.uk
    restart: always

  sqldb:
    image: mariadb:10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=solarsystem
      - MYSQL_USER=solar
      - MYSQL_PASSWORD=system
    volumes:
      - mariadb:/var/lib/mysql:z
    restart: always

  d2r:
    image: cloudfluff/d2r
    volumes:
      - solardata:/var/lib/d2rq:z
    environment:
      - D2R_BASEURI=http://localhost:3000/
    links:
      - sqldb
    restart: always

  loadsheets:
    build:
      context: sheets
    volumes:
      - solardata:/data:z
    links:
      - sqldb
    restart: always

volumes:
  mariadb:
  solardata:
