version: '2'

services:

  vis:
    build:
      context: vis
    ports:
      - 3000:3000
    volumes:
      - ./vis:/app:z
    links:
      - d2r

  d2r:
    build:
      context: d2rq
    ports:
      - 2020:2020
    volumes:
      - ./data:/var/lib/d2rq:z
    environment:
      - D2R_BASEURI=http://localhost:3000/

  loadsheets:
    build:
      context: sheets
    volumes:
      - ./data:/data:z
      - ./sheets:/usr/local/sheets:z
