version: '3.8'

services:

  vis:
    build:
      context: vis
    links:
      - d2r
      - stats-registry
    environment:
      - VIRTUAL_HOST=solar.ukstats.dev
      - LETSENCRYPT_HOST=solar.ukstats.dev
    restart: always
    networks:
      - cogs_proxy
      - default

  sqldb:
    build:
      context: sqldb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=stats
      - MYSQL_USER=solar
      - MYSQL_PASSWORD=system
    volumes:
      - mariadb:/var/lib/mysql:z
    restart: always

  d2r:
    image: cloudfluff/d2r
    volumes:
      - solardata:/var/lib/d2rq:z
    environment:
      - D2R_BASEURI=https://solar.ukstats.dev/
    links:
      - sqldb
    restart: always

  stats-registry:
    build:
      context: registries
    volumes:
      - registry:/registry:z
      - solardata:/data:z
    links:
      - sqldb
    restart: always

volumes:
  mariadb:
  solardata:
  registry:

networks:
  cogs_proxy:
    external: true
